
class Constantes:
    TOTAL_ROUND = 3
    CONSONANTES = ["BCDFGHJKLMNÑPQRSTVWXYZ"]
    VOCALES = ["AEIOU"]
    VOCAL_PRECIO = 250
    RECOMPENSA_PANEL = 500
    ABECEDARIO = CONSONANTES.append(VOCALES)
